# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  connection-timeout: 5000ms
  servlet:
    context-path: /fagaiwei_api

spring:
  # 环境 dev|test|prod
  profiles:
    active: @profileActive@
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

app:
  path:
    work-dir: ${user.home}/fagaiwei
    userDir: ${user.dir}/fagaiwei
    module:
      report: ${user.dir}/fagaiwei/report
      reportResult: ${user.dir}/fagaiwei/reportResult
    temp: /temp
    upload: /upload

#启用CA登录配置
ca:
  valid: true

##ssh连接配置
#ssh:
#  host: 10.1.3.239
#  port: 22
#  user: root
#  pass: 123456
#  url: http://localhost:8082/
