spring:
    profiles:
        include: db

mysql:
    url: jdbc:mysql://10.1.0.151:3306/zhjg?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456


#logPath: E:/0729/demo_logs
