spring:
    profiles:
        include: db

mysql:
    url: jdbc:mysql://10.1.0.139:3306/zhjg_b?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

hive:
    #  公司测试环境
    user: hdfs
    password:
    url: jdbc:hive2://10.1.3.238:10000/zhjg
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    filters: stat
    initialSize: 2
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 500

#连接远程服务器配置
ssh:
    host: 10.1.3.239
    port: 22
    user: root
    pass: 123456
    url: http://10.1.3.239:8082/
